# Generated by Django 5.0.2 on 2025-06-09 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_announcement_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='student',
            field=models.ForeignKey(blank=True, help_text='If set, this announcement is only visible to this specific student', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
